# Generated by Django 3.0.6 on 2020-05-09 17:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200509_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_place',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('O', 'O(I)'), ('A', 'A(II)'), ('B', 'B(III)'), ('AB', 'AB(IV)')], max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='cnp',
            field=models.CharField(blank=True, max_length=13, unique=True, verbose_name='numeric personal code'),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='rhesus_factor',
            field=models.CharField(blank=True, choices=[('+', 'Positive'), ('-', 'Negative')], max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
